[package]
name = "lexcode"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
serde = { version= "1.0.228", features = ["derive"] }

[dev-dependencies]
proptest = "1.10.0"
proptest-derive = "0.8.0"
